const keymirror = require('keymirror');

module.exports = keymirror({
  ECHO: null,
  BLE_CMD : null,
  GET_EXCHANGE_RATE : null,
  GET_TX_FEE : null,
  GET_TX_INFO : null,
  PREPARE_SIGN_DATA : null,
  DO_TRANSACTION : null,
  GENERATE_TX : null,
  GEN_MNEMONIC: null,
  CREATE_WALLET : null,
  FINISH_BACKUP : null,
  RECOVER_WALLET : null,
  NEW_ADDRESS : null,
  SETUP_ACCOUNT: null,
  GET_TX_HISTORY: null,
  GET_BALANCE : null,
  GET_CARD_INFO : null,
  UPDATE_KEYID: null,
  GET_KEYID: null,
  SYNC_KEYID: null,
  FREEZE_PAIR : null,
  UNFREEZE_PAIR : null,
  GET_PAIRED_DEVICES : null,
  REMOVE_DEVICE : null,
  RENAME_DEVICES : null,
  UPDATE_READTYPE : null,
  UPDATE_BALANCE : null,
  GET_READTYPE_VERSIONS : null,
  GET_SE_VERSION: null,
  GENERATE_APP_KEY : null,
  REGISTER_DEVICE : null,
  RESET_PAIR : null,
  GET_CARD_INFO : null,
  CANCEL_APDU : null,
  TIMEOUT_CANCEL : null,
  GET_PAIR_PWD : null,
  SHOW_FULL_ADDRESS : null,
  APDU_TEST : null,
  IS_APPLET_EXIST : null,
  SE_UPDATE : null,
  IS_NEED_SE_UPDATE : null,
  DFU_UPDATE : null,
  DFU_BATCH_CMD : null,
  PROGRESS: null,
  TX_PREP_COMPLETE: null,
  TX_AUTHORIZE: null,
  GET_CALCULATING_FEE: null,
  GET_UTXO : null
});
